spring.application.name=hotelsearch

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=hotel-search-consumer-group

app.kafka.topic.hotel-availability-searches=hotel_availability_searches

management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.path=/swagger-ui.html