spring.application.name=hotelsearch
spring.threads.virtual.enabled=true
spring.kafka.listener.concurrency=5

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=hotel_user
spring.datasource.password=hotel_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=hotel-search-consumer-group
app.kafka.topic.hotel-availability-searches=hotel_availability_searches

management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.path=/swagger-ui.html